.*: Assembler messages:
.*: Error: Instruction p.addn requires absolute expression
.*: Error: Instruction p.addun requires absolute expression
.*: Error: Instruction p.addrn requires absolute expression
.*: Error: Instruction p.addurn requires absolute expression
.*: Error: Instruction p.subn requires absolute expression
.*: Error: Instruction p.subun requires absolute expression
.*: Error: Instruction p.subrn requires absolute expression
.*: Error: Instruction p.suburn requires absolute expression
