.*: Assembler messages:
.*: Error: -1 constant out of range for lp.starti, range:\[0, 8190\]
.*: Error: -1 constant out of range for lp.endi, range:\[0, 8190\]
.*: Error: -1 constant out of range for lp.setup, range:\[0, 8190\]
.*: Error: -6 constant out of range for lp.starti, range:\[0, 8190\]
.*: Error: -94 constant out of range for lp.endi, range:\[0, 8190\]
.*: Error: -842 constant out of range for lp.setup, range:\[0, 8190\]
.*: Error: 8944 constant out of range for lp.starti, range:\[0, 8190\]
.*: Error: 20394 constant out of range for lp.setup, range:\[0, 8190\]
