.*: Assembler messages:
.*: Error: illegal operands `p.clip t0,t3,-1'
.*: Error: illegal operands `p.clipu t0,t3,-1'
.*: Error: illegal operands `p.clip t0,t3,-400'
.*: Error: illegal operands `p.clipu t0,t3,-985'
.*: Error: illegal operands `p.clip t0,t3,32'
.*: Error: illegal operands `p.clipu t0,t3,32'
.*: Error: illegal operands `p.clip t0,t3,859'
.*: Error: illegal operands `p.clipu t0,t3,7283'
